title: The Cyber Convex

description: >-
  Company website 2020.
baseurl: ""
url: ""
twitter_username: thecyberconvex
github_username:  thecyberconvex

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
